### ISSUE TITLE
How much of this can be public?

### ISSUE THREAD

**Issue by kpu** [paracrawl/cirrus-scripts#19]
This is a private repo.  Should e.g. https://github.com/paracrawl/cirrus-scripts/blob/master/mt-filter-list.annotated be public and open source?

**Comment by jelmervdl** [comment]
I've removed the GDPR filter list [using `git filter-branch`](https://docs.github.com/en/github/authenticating-to-github/removing-sensitive-data-from-a-repository#using-filter-branch).

There are still paths on CSD3 & Cirrus which contain our usernames there, and Slurm account names, but I doubt those will be useful to anyone.
